FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y poppler-utils tesseract-ocr tesseract-ocr-tha && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]